sonar.projectKey=webapp-component-ui-main
sonar.projectName=webapp-component-ui (main)

sonar.sources=src
sonar.tests=tests

sonar.issue.ignore.multicriteria=noTodoTags
sonar.issue.ignore.multicriteria.noTodoTags.ruleKey=javascript:S1135
sonar.issue.ignore.multicriteria.noTodoTags.resourceKey=**/*
